// <auto-generated />
namespace BullsAndCows.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updategameaddbullsprop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updategameaddbullsprop));
        
        string IMigrationMetadata.Id
        {
            get { return "201804171746262_Update-game-add-bulls-prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
